name: Say hello

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        required: true
        options:
          - monalisa
          - cschleiden
      limit-page:
        type: choice
        description: select limit page
        required: true
        options:
          - "10"
          - "100"
          - "1000"
          - "10000"

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola midu!"
      - name: Dime la fecha
        run: date
      - run: ls -l